### ISSUE TITLE
Drop down menu's texts are in white.

### ISSUE THREAD

**Issue by chakler** [donnieberg/accessible-color-palette#1]
Drop down menu's texts are in white, they are probably affected by the ".inputColor" class.

![file 2-25-15 1 00 47 pm](https://cloud.githubusercontent.com/assets/3196969/6365254/f1c2d91c-bcee-11e4-8e72-e246525be948.jpeg)

**Comment by donnieberg** [comment]
Thanks so much for catching this! Which browser/os are you on?

**Comment by chakler** [comment]
No problem! Chrome on Windows 8.1.
