### ISSUE TITLE
Color Tile screen scroll bug

### ISSUE THREAD

**Issue by jgarber623** [donnieberg/accessible-color-palette#2]
The final screen with the color tiles does not correctly scroll into view in Firefox.

For reference, I made [this screen recording](http://f.cl.ly/items/0b20041G161f1e1m333f/generate-button-bug.m4v) showing the issue.

My guess is that there's a bug in how (or when) the scroll offset is being calculated.
## Steps to reproduce
1. Use [colorsafe.co](http://colorsafe.co) in Mozilla Firefox (36.0, Mac OS X Yosemite).
2. Click "Get Started"
3. Click "Generate Color Palette"
4. Observe the extra spacing between the page's header and the color tiles.

**Comment by donnieberg** [comment]
thanks for the video! I'll look into that now.

**Comment by donnieberg** [comment]
It was a wonky css animation that was broken. Fixed :)
