### ISSUE TITLE
Minify and concatenate CSS and JavaScript

### ISSUE THREAD

**Issue by jgarber623** [donnieberg/accessible-color-palette#3]
I ran [colorsafe.co](http://colorsafe.co/) through [Google's PageSpeed Insights tool](https://developers.google.com/speed/pagespeed/insights/) and it came back with several useful recommendations.

[Full Google PageSpeed Insights report](https://developers.google.com/speed/pagespeed/insights/?url=colorsafe.co)
## Minification
- [ ] Minify `i.css`: "Minifying http://colorsafe.co/css/i.css could save 1.2KiB (21% reduction) after compression."
- [ ] Minify `tinycolor.js`, `app.js`, `/bootstrap-colorpicker-module.js`, etc.: "Minify JavaScript for the following resources to reduce their size by 6.2KiB (9% reduction)."
## Concatenation

Similarly, concatenating CSS and JavaScript files into single CSS and JS files greatly reduces page load time by eliminating unnecessary HTTP requests.
- [ ] Concatenate CSS files into a single `app.css` file.
- [ ] Concatenate JavaScript files into a single `app.js` file.

It appears you're [already using Gulp](https://github.com/donnieberg/accessible-color-palette/blob/master/gulpfile.js) to some degree so additional minification and concatenation _might_ be pretty straightforward.

**Comment by donnieberg** [comment]
This google tool is amazing! Thanks for sharing it with me. I minified/concatenated the css files and most of the js files which will hopefully make the site run a bit faster. Thanks again for your knowledgeable, clear, and helpful comments! I can't tell you how much I appreciate them.

**Comment by jgarber623** [comment]
Sure thing! Happy to help out. :smile:
