### ISSUE TITLE
Use <button> instead of <a href="javascript:void(0)">

### ISSUE THREAD

**Issue by jgarber623** [donnieberg/accessible-color-palette#4]
There are a number of instances where the pattern `<a href="javascript:void(0)"> is used. For instance, the "close" button on the slide out left sidebar uses this pattern.

Anchors are typically used for linking between and within documents with URLs or fragment identifiers as `href`s. I recommend using the `<button type="button">` element and attaching the relevant behavior to that element in place of `<a href="javascript:void(0)">`.

**Comment by donnieberg** [comment]
That makes a lot of sense and is more semantic. Thanks!
