### ISSUE TITLE
Add `role="contentinfo"` to slide out left panel

### ISSUE THREAD

**Issue by jgarber623** [donnieberg/accessible-color-palette#5]
The [`contentinfo` landmark role](http://www.w3.org/TR/wai-aria/roles#contentinfo), according to the spec:

> A large perceivable region that contains information about the parent document. Examples of information included in this region of the page are copyrights and links to privacy statements. 

I'd say the [slide out left panel](http://cl.ly/image/3E352n151i3N) fits that description nicely!

**Comment by donnieberg** [comment]
Awesome! Thanks so much for this. Just added it.
