### ISSUE TITLE
Contrast ratio for AA large text is 3.0

### ISSUE THREAD

**Issue by ojbaharav** [donnieberg/accessible-color-palette#6]
According to WCAG2.0, guideline 1.4.3 Contrast (Minimum) for large text:

> Large-scale text and images of large-scale text have a contrast ratio of at least 3:1.

http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

Current ratio in Colorsafe is 1:3.1, it is a mistake.

**Comment by donnieberg** [comment]
Thanks so much for flagging this! I changed 3.1 to 3.

**Comment by ojbaharav** [comment]
Good :) Can you publish that at Colorsafe.co please?

**Comment by donnieberg** [comment]
Pushed! :) Thanks again for your feedback.
